# Generated by Django 3.1.6 on 2021-02-02 17:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('eDuka', '0007_auto_20210202_1335'),
    ]

    operations = [
        migrations.RenameField(
            model_name='item',
            old_name='Product',
            new_name='product',
        ),
    ]
