# Generated by Django 3.1.6 on 2021-02-04 00:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eDuka', '0010_auto_20210203_1928'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(max_length=30)),
            ],
        ),
    ]
