# Generated by Django 3.1.6 on 2021-02-04 06:52

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('eDuka', '0011_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='posted_date',
            field=models.DateTimeField(auto_now_add=True, default=1),
            preserve_default=False,
        ),
    ]
