# Generated by Django 3.1.6 on 2021-02-04 21:16

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('eDuka', '0014_comment'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='description',
            field=models.TextField(default=django.utils.timezone.now, max_length=150),
            preserve_default=False,
        ),
    ]
